/* Generated by MyraPad at 06.06.2020 15:12:34 */
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;

#if !XENKO
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#else
using Xenko.Core.Mathematics;
#endif

namespace NoisEvader.UI
{
	partial class ArenaPause: VerticalStackPanel
	{
		private void BuildUI()
		{
			Restart = new TextButton("PauseScreenBtn");
			Restart.Text = "Restart";
			Restart.TextColor = Color.White;
			Restart.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			Restart.Id = "Restart";

			Continue = new TextButton("PauseScreenBtn");
			Continue.Text = "Resume";
			Continue.TextColor = Color.White;
			Continue.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			Continue.Id = "Continue";

			Exit = new TextButton("PauseScreenBtn");
			Exit.Text = "Quit";
			Exit.TextColor = Color.White;
			Exit.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			Exit.Id = "Exit";

			
			Spacing = 50;
			HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			Widgets.Add(Restart);
			Widgets.Add(Continue);
			Widgets.Add(Exit);
		}

		
		public TextButton Restart;
		public TextButton Continue;
		public TextButton Exit;
	}
}