/* Generated by MyraPad at 04.10.2020 21:27:40 */
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;

#if !STRIDE
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#else
using Stride.Core.Mathematics;
#endif

namespace NoisEvader.UI
{
	partial class LevelSettingsWindow: Window
	{
		private void BuildUI()
		{
			ThirtyTicks = new CheckBox();
			ThirtyTicks.Text = " Force 30 ticks/sec.";
			ThirtyTicks.TextColor = Color.White;
			ThirtyTicks.ImageWidth = 16;
			ThirtyTicks.ImageHeight = 16;
			ThirtyTicks.Id = "ThirtyTicks";

			NaiveWarp = new CheckBox();
			NaiveWarp.Text = " Emulate Sdgr+ timewarp/spinrate calc.";
			NaiveWarp.TextColor = Color.White;
			NaiveWarp.ImageWidth = 16;
			NaiveWarp.ImageHeight = 16;
			NaiveWarp.Id = "NaiveWarp";

			var horizontalSeparator1 = new HorizontalSeparator();
			horizontalSeparator1.Thickness = 2;
			horizontalSeparator1.Padding = new Thickness(0, 5);

			InvertColors = new CheckBox();
			InvertColors.Text = " Invert colors";
			InvertColors.TextColor = Color.White;
			InvertColors.ImageWidth = 16;
			InvertColors.ImageHeight = 16;
			InvertColors.Id = "InvertColors";

			Ok = new TextButton();
			Ok.Text = "OK";
			Ok.TextColor = Color.White;
			Ok.Margin = new Thickness(0, 10, 0, 0);
			Ok.Padding = new Thickness(5);
			Ok.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			Ok.Id = "Ok";

			MainPanel = new VerticalStackPanel();
			MainPanel.Id = "MainPanel";
			MainPanel.Widgets.Add(ThirtyTicks);
			MainPanel.Widgets.Add(NaiveWarp);
			MainPanel.Widgets.Add(horizontalSeparator1);
			MainPanel.Widgets.Add(InvertColors);
			MainPanel.Widgets.Add(Ok);

			
			Title = "Level Settings";
			Left = 382;
			Top = 107;
			Padding = new Thickness(10);
			Content = MainPanel;
		}

		
		public CheckBox ThirtyTicks;
		public CheckBox NaiveWarp;
		public CheckBox InvertColors;
		public TextButton Ok;
		public VerticalStackPanel MainPanel;
	}
}