/* Generated by MyraPad at 24.09.2020 16:54:33 */
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;

#if !XENKO
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#else
using Xenko.Core.Mathematics;
#endif

namespace NoisEvader.UI
{
	partial class LevelPositionScreen: Grid
	{
		private void BuildUI()
		{
			Position = new HorizontalSlider();
			Position.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			Position.Maximum = 1;
			Position.Width = 500;
			Position.Id = "Position";

			var panel1 = new Panel();
			panel1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			panel1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			panel1.Padding = new Thickness(0, 0, 0, 30);
			panel1.Widgets.Add(Position);

			
			Widgets.Add(panel1);
		}

		
		public HorizontalSlider Position;
	}
}