/* Generated by MyraPad at 01.10.2020 18:25:11 */
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;

#if !XENKO
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#else
using Xenko.Core.Mathematics;
#endif

namespace NoisEvader.UI
{
	partial class MainMenu: VerticalStackPanel
	{
		private void BuildUI()
		{
			Version = new Label();
			Version.Text = "0.0.0";
			Version.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			Version.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			Version.Id = "Version";

			Logo = new Image();
			Logo.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			Logo.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			Logo.Id = "Logo";

			Play = new TextButton("MainMenuBtn");
			Play.Text = "Play";
			Play.TextColor = Color.White;
			Play.Id = "Play";

			Settings = new TextButton("MainMenuBtn");
			Settings.Text = "Settings";
			Settings.TextColor = Color.White;
			Settings.Id = "Settings";

			Exit = new TextButton("MainMenuBtn");
			Exit.Text = "Quit";
			Exit.TextColor = Color.White;
			Exit.Id = "Exit";

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Spacing = 10;
			horizontalStackPanel1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			horizontalStackPanel1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			horizontalStackPanel1.Margin = new Thickness(0, 30, 0, 0);
			horizontalStackPanel1.Widgets.Add(Play);
			horizontalStackPanel1.Widgets.Add(Settings);
			horizontalStackPanel1.Widgets.Add(Exit);

			
			Spacing = 10;
			HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			Widgets.Add(Version);
			Widgets.Add(Logo);
			Widgets.Add(horizontalStackPanel1);
		}

		
		public Label Version;
		public Image Logo;
		public TextButton Play;
		public TextButton Settings;
		public TextButton Exit;
	}
}