/* Generated by MyraPad at 07.05.2020 20:11:05 */
using System;
using System.Diagnostics;
using Microsoft.Xna.Framework;
using Myra.Graphics2D.UI;

namespace NoisEvader.UI
{
    public partial class ModWindow
    {
        private Mod mod;
        public Mod Mod { get => mod; set => mod = value; }

        public ModWindow()
        {
            BuildUI();

            Showcase.Click += Showcase_Click;
            Zen.Click += Zen_Click;
            Live.Click += Live_Click;
            GameSpeed.ValueChanged += GameSpeed_ValueChanged;
            ChangeGameSpeed.Click += ChangeGameSpeed_Click;
            Flashlight.Click += Flashlight_Click;
        }

        private void Flashlight_Click(object sender, EventArgs e)
        {
            Mod.SetMod(ref mod, ModFlags.Flashlight, Flashlight.IsPressed);
        }

        private void ChangeGameSpeed_Click(object sender, EventArgs e)
        {
            SetGameSpeed();
        }

        private void GameSpeed_ValueChanged(object sender, Myra.Utility.ValueChangedEventArgs<float> e)
        {
            SetGameSpeed();
        }

        private void SetGameSpeed()
        {
            var gs = (float)Math.Truncate(GameSpeed.Value * 10) / 10;
            GameSpeedLabel.Text = $"{gs}x";
            mod.GameSpeed = ChangeGameSpeed.IsPressed ? gs : 1;
        }

        private void Live_Click(object sender, System.EventArgs e)
        {
            Mod.SetMod(ref mod, ModFlags.Live, Live.IsPressed);
        }

        private void Zen_Click(object sender, System.EventArgs e)
        {
            Mod.SetMod(ref mod, ModFlags.Zen, Zen.IsPressed);
            if (Zen.IsPressed)
            {
                Mod.SetMod(ref mod, ModFlags.Showcase, !Zen.IsPressed);
                Showcase.IsPressed = false;
            }
        }

        private void Showcase_Click(object sender, System.EventArgs e)
        {
            Mod.SetMod(ref mod, ModFlags.Showcase, Showcase.IsPressed);
            if (Showcase.IsPressed)
            {
                Mod.SetMod(ref mod, ModFlags.Zen, !Showcase.IsPressed);
                Zen.IsPressed = false;
            }
        }

    }
}