/* Generated by MyraPad at 02.05.2020 23:18:31 */
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;

#if !XENKO
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#else
using Xenko.Core.Mathematics;
#endif

namespace NoisEvader.UI
{
	partial class ScoreScreen: Grid
	{
		private void BuildUI()
		{
			Score = new Label();
			Score.Text = "99%";
			Score.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			Score.GridRow = 1;
			Score.Id = "Score";

			Back = new TextButton();
			Back.Text = "Back";
			Back.Padding = new Thickness(5);
			Back.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			Back.GridRow = 2;
			Back.Id = "Back";

			
			RowSpacing = 40;
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			Widgets.Add(Score);
			Widgets.Add(Back);
		}

		
		public Label Score;
		public TextButton Back;
	}
}